// <auto-generated>
// This file is generated by UiRegionElementAddressableIdsGenerator.
// </auto-generated>

namespace GameKit.UiRegionsControl.Contracts
{
    public static class UiRegionElementAddressableIds
    {
        public const string k_CorePage = "CorePage";
        public const string k_CorePageBackground = "CorePageBackground";
        public const string k_ErrorPopup = "ErrorPopup";
        public const string k_MetaPage = "MetaPage";
        public const string k_MetaPageBackground = "MetaPageBackground";
        public const string k_PopupBackdrop = "PopupBackdrop";
        public const string k_SettingsPopup = "SettingsPopup";
        public const string k_TopPanel = "TopPanel";
#if !IS_PRODUCTION
        public const string k_CurrenciesDebugPage = "CurrenciesDebugPage";
        public const string k_DebugPageBackdrop = "DebugPageBackdrop";
        public const string k_DebugPanelMessage = "DebugPanelMessage";
        public const string k_DebugPanelTabBar = "DebugPanelTabBar";
        public const string k_EnergyDebugPage = "EnergyDebugPage";
        public const string k_LogsDebugPage = "LogsDebugPage";
        public const string k_StateDebugPage = "StateDebugPage";
        public const string k_TimeDebugPage = "TimeDebugPage";
#endif
    }
}
