using System;
using System.Collections.Generic;
using System.IO;
using System.Text;
using GameKit.UiRegions;
using UnityEditor;
using UnityEditor.AddressableAssets;
using UnityEngine;

namespace GameKit.UiRegionsControl.Editor
{
    public static class UiRegionElementAddressableIdsGenerator
    {
        private const string k_MenuItemPath = "GameKit/Rebuild UI Region Element Addressable Ids";
        private const string k_OutputRelativePathFromModuleRoot = "Contracts/UiRegionElementAddressableIds.Generated.cs";

        [MenuItem(k_MenuItemPath, false, 103)]
        public static void Generate()
        {
            var generatedCode = BuildGeneratedCode();
            var outputAssetPath = GetOutputFileAssetPath();
            var fullOutputPath = GetAbsoluteProjectPath(outputAssetPath);
            var outputDirectoryPath = Path.GetDirectoryName(fullOutputPath);

            if (!string.IsNullOrEmpty(outputDirectoryPath))
            {
                Directory.CreateDirectory(outputDirectoryPath);
            }

            if (File.Exists(fullOutputPath))
            {
                var existingCode = File.ReadAllText(fullOutputPath);
                if (existingCode == generatedCode)
                {
                    Debug.Log("UI region element addressable ids are already up to date.");
                    return;
                }
            }

            File.WriteAllText(fullOutputPath, generatedCode, Encoding.UTF8);
            AssetDatabase.ImportAsset(outputAssetPath);
        }

        private static string BuildGeneratedCode()
        {
            var (mainAddressableIds, debugAddressableIds) = CollectAddressableIds();
            var builder = new StringBuilder();

            builder.AppendLine("// <auto-generated>");
            builder.AppendLine("// This file is generated by UiRegionElementAddressableIdsGenerator.");
            builder.AppendLine("// </auto-generated>");
            builder.AppendLine();
            builder.AppendLine("namespace GameKit.UiRegionsControl");
            builder.AppendLine("{");
            builder.AppendLine("    public static class UiRegionElementAddressableIds");
            builder.AppendLine("    {");

            foreach (var mainAddressableId in mainAddressableIds)
            {
                builder.Append("        public const string ");
                builder.Append(ToConstantName(mainAddressableId));
                builder.Append(" = \"");
                builder.Append(mainAddressableId);
                builder.AppendLine("\";");
            }

            builder.AppendLine("#if !IS_PRODUCTION");
            foreach (var debugAddressableId in debugAddressableIds)
            {
                builder.Append("        public const string ");
                builder.Append(ToConstantName(debugAddressableId));
                builder.Append(" = \"");
                builder.Append(debugAddressableId);
                builder.AppendLine("\";");
            }
            builder.AppendLine("#endif");

            builder.AppendLine("    }");
            builder.AppendLine("}");

            return builder.ToString();
        }

        private static (List<string> mainIds, List<string> debugIds) CollectAddressableIds()
        {
            var mainIds = new List<string>();
            var debugIds = new List<string>();
            var settings = AddressableAssetSettingsDefaultObject.Settings;

            if (!settings)
            {
                return (mainIds, debugIds);
            }

            var prefabGuids = AssetDatabase.FindAssets("t:Prefab");
            foreach (var prefabGuid in prefabGuids)
            {
                var prefabPath = AssetDatabase.GUIDToAssetPath(prefabGuid);
                var prefab = AssetDatabase.LoadAssetAtPath<GameObject>(prefabPath);
                if (!prefab)
                {
                    continue;
                }

                var regionElement = prefab.GetComponent<UiRegionElement>();
                if (!regionElement)
                {
                    continue;
                }

                var entry = settings.FindAssetEntry(prefabGuid);
                if (entry == null || string.IsNullOrEmpty(entry.address))
                {
                    continue;
                }

                if (regionElement.IsDebug)
                {
                    debugIds.Add(entry.address);
                }
                else
                {
                    mainIds.Add(entry.address);
                }
            }

            mainIds.Sort();
            debugIds.Sort();
            return (mainIds, debugIds);
        }

        private static string ToConstantName(string addressableId)
        {
            var builder = new StringBuilder("k_");
            var capitalizeNext = true;

            foreach (var symbol in addressableId)
            {
                if (!char.IsLetterOrDigit(symbol))
                {
                    capitalizeNext = true;
                    continue;
                }

                builder.Append(capitalizeNext ? char.ToUpperInvariant(symbol) : symbol);
                capitalizeNext = false;
            }

            return builder.ToString();
        }

        private static string GetOutputFileAssetPath()
        {
            var generatorScriptPath = GetGeneratorScriptAssetPath();
            var editorDirectoryPath = Path.GetDirectoryName(generatorScriptPath);
            var moduleRootPath = Path.GetDirectoryName(editorDirectoryPath);

            return Path.Combine(moduleRootPath ?? string.Empty, k_OutputRelativePathFromModuleRoot).Replace("\\", "/");
        }

        private static string GetGeneratorScriptAssetPath()
        {
            var scriptGuids = AssetDatabase.FindAssets($"{nameof(UiRegionElementAddressableIdsGenerator)} t:Script");
            foreach (var scriptGuid in scriptGuids)
            {
                var scriptPath = AssetDatabase.GUIDToAssetPath(scriptGuid);
                if (Path.GetFileNameWithoutExtension(scriptPath) == nameof(UiRegionElementAddressableIdsGenerator))
                {
                    return scriptPath;
                }
            }

            throw new InvalidOperationException($"Could not resolve the asset path for {nameof(UiRegionElementAddressableIdsGenerator)}.");
        }

        private static string GetAbsoluteProjectPath(string assetPath)
        {
            var projectRootPath = Directory.GetParent(Application.dataPath)?.FullName;
            if (string.IsNullOrEmpty(projectRootPath))
            {
                throw new InvalidOperationException("Project root path could not be resolved.");
            }

            return Path.GetFullPath(Path.Combine(projectRootPath, assetPath));
        }
    }
}
